### ISSUE TITLE
Avoid using module globals for file_loading.py

### ISSUE THREAD

**Issue by bbonf** [CentreForDigitalHumanities/django-shared-core#50]
See https://github.com/DH-IT-Portal-Development/django-shared-core/blob/develop/cdh/core/file_loading.py#L3
and https://github.com/DH-IT-Portal-Development/django-shared-core/blob/develop/cdh/core/templatetags/file_loading.py#L3

This causes some weird interaction between requests etc. (and would probably also behave differently between a local dev server and prod)

**Comment by tymees** [comment]
Yeah, we probably need to use ThreadLocalUserMiddleWare https://github.com/DH-IT-Portal-Development/django-shared-core/blob/2c21dcc067c6ed9d6ee9eb686c6c98854f9ef2be/cdh/core/middleware/local_thread_middleware.py#L33

Well, and rename that to be more generic

**Comment by tymees** [comment]
Okay I've explored the issue further, and have decided that this approach is fundamentally flawed.

This project only uses it to load js/css needed for form elements, which can also be loaded through Django's [Form Assets system](https://docs.djangoproject.com/en/dev/topics/forms/media/#topics-forms-media). So I'm probably going to rewrite the usages in this project to use that instead. (And add some template stuff that will try to load form assets automatically).

... I probably should've done that in the first place. 

Do you have any other usages that might not fit this solution?

**Comment by bbonf** [comment]
I think an alternative solution would be a good idea. I think I've only used these functions via the TinyMCE widget

**Comment by tymees** [comment]
3.2 now uses the form-assets system
