### ISSUE TITLE
Missing django-filter dependency?

### ISSUE THREAD

**Issue by bbonf** [CentreForDigitalHumanities/django-shared-core#96]
Imported in fancylist_api_view.py

See https://github.com/UiL-OTS-labs/web-experiment-datastore/actions/runs/7386385798/job/20092859640

**Comment by tymees** [comment]
_Great, somehow this repo mails my personal email..._

Hmmm, why does this not cause issues anywhere else?

In any case, the import in that file was incorrect and has been removed. `django-filter` is a dependency of fancylist's replacement, but well, that's not this. :P
