### ISSUE TITLE
Problems with extended template and TemplateEmail

### ISSUE THREAD

**Issue by bbonf** [CentreForDigitalHumanities/django-shared-core#97]
I'm trying to have the following setup where:

`base.html` extends from `cdh.core/mail_template.html` and defines only a footer block.
`target.html` extends from `base.html` and defines only content and banner blocks, while inheriting the footer from base.

By default this doesn't work, because TemplateEmail sets `has_footer` to false, as it can't find a footer block in `target.html` (see https://github.com/CentreForDigitalHumanities/django-shared-core/blob/master/src/cdh/core/mail/classes.py#L370).
If I try to circumvent that, by having a footer block that only calls super, then I get an error from somewhere deeper in the stack: `AttributeError: 'NoneType' object has no attribute 'engine'`

Am I missing anything? any idea for a workaround?

**Comment by tymees** [comment]
I'll have a better look at the exact issue later, but as for a workaround:

You could separate your footer into a file you then include in every mail. It kinda defeats the purpose of using base-templates, but well, it would work...

**Comment by bbonf** [comment]
I think I've narrowed down the `NoneType` error to the use of `lru_cache` here: https://github.com/CentreForDigitalHumanities/django-shared-core/blob/9d4536b4dd775d49a541180c36bdd997ded60ec0/src/cdh/core/mail/classes.py#L607

I can't explain the reason, but something doesn't like being cached maybe?

**Comment by tymees** [comment]
Hmmmm, that cache is not really required (more of a small optimization). So if removing that fixes the error I would say we should do that

**Comment by bbonf** [comment]
So removing `lru_cache` seemed to fix the issue in one place*, but I've ran into it again with another email.

It's somehow triggered by the `BlockNode.render()` call in the flow that handles emails with no `plain_template`:
https://github.com/CentreForDigitalHumanities/django-shared-core/blob/master/src/cdh/core/mail/classes.py#L382
If I specify a `plain_template`, the error is gone.

(* it could also be that it didn't really fix the issue in the first place, but it was randomly correlated)

**Comment by tymees** [comment]
Yeah I think the real issue is that extracting template data like this only really works with only the one level of extension.

At this point I would recommend creating your own email base-template by copy/pasting the shipped version; at least for now until I've had the time to sit down and debug it more.

**Comment by bbonf** [comment]
I think I've just run into a related issue with web-experiment-datastore:

https://github.com/UiL-OTS-labs/web-experiment-datastore/blob/develop/experiments/utils/mails.py#L15
throws
`'ExtendsNode' object is not iterable`

**Comment by tymees** [comment]
I've been able to track down that error, and have temporary fix for it.

However, while looking at that I think I can find a solution for your other bug. Let me set up a better dev env for this and I'll get back to you

**Comment by tymees** [comment]
I think the new `cdh.mail` fixes all these problems, right?
